project:
  type: website
  output-dir: docs

website:
  title: "Olympic Swimming Analysis"
  navbar:
    logo: "images/olympic_rings.png" # <--- CHANGED TO A DIRECT STRING PATH
    left:
      - href: index.qmd
        text: Home
      - href: distribution.qmd 
        text: Medal Map   
      - href: sources.qmd
        text: Sources
      - href: about.qmd
        text: About


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true